Moore voting algorithm
dheeraj-2000/dsalgo pull request #48
Opened 2020-10-08 15:15 UTC by rohanmahto592

2020-10-08 15:41 UTC, dheeraj-2000 requested changes
@rohanmahto592 Thank you for contributing, please do few minor change:
- As you're adding an algorithm, so it'll be good if you mention **Time & Space complexities.**.

    _*Also adding some description/comments will be more appreciable._

2020-10-10 06:39 UTC, rohanmahto592 reviewed
changed.

2020-10-10 10:58 UTC, dheeraj-2000 approved these changes

2020-10-10 10:58 UTC, merged

2020-10-10 11:19 UTC, dheeraj-2000 commented
@rohanmahto592 Though I've merged your PR assuming you're a beginner, there are few things you should take care for future contributions (just a suggestion):
- You should've given your file extension as **.cpp** instead of **.txt** (or the extension of your programming language)
- I was expecting the desciption of the Problem statement in the code file, this way it'll help everyone who's looking at your code.

All the best :+1: 
Thanks for your contribution :v: